// frontend/src/components/pdf/GradingReportPDF.tsx
import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdfConfig";
import type { GradeResponse } from "../../types/grading";

interface Props {
  data: GradeResponse;
  fileName?: string;
  showReference?: boolean; // [新增] 控制是否显示参考答案
}

export const GradingReportPDF: React.FC<Props> = ({ 
  data, 
  fileName, 
  showReference = false 
}) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>Grading Report</Text>
            <Text style={styles.subTitle}>Generated by AI Grading System</Text>
          </View>
          <View style={{ alignItems: "flex-end" }}>
            <Text style={styles.subTitle}>{new Date().toLocaleDateString()}</Text>
            <Text style={styles.subTitle}>{fileName || "Student Submission"}</Text>
          </View>
        </View>

        {/* Overall Score */}
        <View style={styles.scoreBox}>
          <Text style={{ fontSize: 14, fontWeight: 'bold' }}>Overall Score</Text>
          <Text style={styles.scoreValue}>{data.overall_score}</Text>
        </View>

        {/* Overall Feedback */}
        <View>
          <Text style={styles.sectionTitle}>Overall Feedback</Text>
          <Text style={styles.text}>{data.overall_comment || "No feedback provided."}</Text>
        </View>

        {/* Rubric Details Table */}
        {data.rubric_scores && data.rubric_scores.length > 0 && (
          <View>
            <Text style={styles.sectionTitle}>Detailed Evaluation</Text>
            <View style={styles.table}>
              {/* Table Header */}
              <View style={[styles.tableRow, styles.tableHeader]}>
                <Text style={styles.col1}>Criterion</Text>
                <Text style={styles.col2}>Score</Text>
                <Text style={styles.col3}>Comment</Text>
              </View>
              {/* Table Body */}
              {data.rubric_scores.map((item, index) => (
                <View key={index} style={styles.tableRow}>
                  <Text style={styles.col1}>{item.criterion}</Text>
                  <Text style={styles.col2}>{item.score}</Text>
                  <Text style={styles.col3}>{item.comment}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* [新增] Reference Answer Section (Conditional) */}
        {showReference && data.reference_answer && (
          <View wrap={false} style={{ marginTop: 20 }}>
            <Text style={styles.sectionTitle}>Reference Answer</Text>
            <View style={{ padding: 10, backgroundColor: "#f8fafc", borderRadius: 4 }}>
              <Text style={{ fontSize: 10, fontFamily: "Helvetica", color: "#334155" }}>
                {data.reference_answer}
              </Text>
            </View>
          </View>
        )}
      </Page>
    </Document>
  );
};